### ISSUE TITLE
 TypeError: tf__sentence_to_index() got an unexpected keyword argument 'oov_index'

### ISSUE THREAD

**Issue by tae-min-lee** [psj8252/quickspacer#6]
모델 training 시키는 작업에서 error가 발생합니다
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/asd3371kr/tasks/spacer/quickspacer/scripts/train_quickspacer.py", line 67, in <module>
    dataset = get_dataset(
  File "/home/asd3371kr/tasks/spacer/quickspacer/quickspacer/data.py", line 37, in get_dataset
    tf.data.TextLineDataset(dataset_file_path, num_parallel_reads=num_parallel_reads)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1658, in map
    return ParallelMapDataset(
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4175, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3323, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2531, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1006, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3316, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3254, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/asd3371kr/tasks/transformers/transformers/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 281, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    TypeError: tf__sentence_to_index() got an unexpected keyword argument 'oov_index'

**Comment by cosmoquester** [comment]
현재 master branch 로 다시 해보실래요?

**Comment by tae-min-lee** [comment]
해결했습니다.! 감사합니다
